- worker:
  - command: roslaunch
  - parameters:
    - ltfnp_executive
    - ltfnp_simulation.launch
    - HEADLESS:=true
  - checklist:
    - item:
      - name: moveit
      - matchmode: match
      - template: "All is well! Everyone is happy! You can start planning now!"
      - message: "MoveIt! launched successfully"
    - item:
      - name: attache
      - matchmode: contains
      - template: "Attache plugin loaded"
      - message: "Attache plugin present"
    - item:
      - name: reasoning
      - matchmode: contains
      - template: "ltfnp_reasoning/prolog/init.pl compiled"
      - message: "Reasoning started successfully"
  - timeout: 180
- worker:
  - command: rosrun
  - parameters:
    - semrec
    - semrec
    - "-q"
    - "-s"
  - checklist:
    - item:
      - name: initialize
      - matchmode: contains
      - template: "Signify: semrec init complete"
      - message: "Semrec Initialized"
  - timeout: 5
- worker:
  - command: rosrun
  - parameters:
    - ltfnp_executive
    - prep_camera.sh
    - 1
  - checklist:
    - item:
      - name: prep_cam
      - matchmode: contains
      - template: "Camera prepared"
      - message: "Camera 1 prepared"
  - timeout: 5
- worker:
  - command: rosrun
  - parameters:
    - ltfnp_executive
    - prep_camera.sh
    - 2
  - checklist:
    - item:
      - name: prep_cam
      - matchmode: contains
      - template: "Camera prepared"
      - message: "Camera 2 prepared"
  - timeout: 5
- worker:
  - command: rosrun
  - parameters:
    - ltfnp_executive
    - prep_camera.sh
    - 3
  - checklist:
    - item:
      - name: prep_cam
      - matchmode: contains
      - template: "Camera prepared"
      - message: "Camera 3 prepared"
  - timeout: 5
- worker:
  - command: rosrun
  - parameters:
    - ltfnp_executive
    - prep_camera.sh
    - 4
  - checklist:
    - item:
      - name: prep_cam
      - matchmode: contains
      - template: "Camera prepared"
      - message: "Camera 4 prepared"
  - timeout: 5
- worker:
  - command: rosrun
  - parameters:
    - ltfnp_executive
    - prep_mongodb.sh
  - checklist:
    - item:
      - name: prep_db
      - matchmode: contains
      - template: "MongoDB shell"
      - message: "MongoDB Logging started"
  - timeout: 10
- worker:
  - command: rosrun
  - parameters:
    - ltfnp_executive
    - start.sh
  - checklist:
    - item:
      - name: connect_ros
      - matchmode: contains
      - template: "Connecting to ROS"
      - message: "Connecting to ROS"
    - item:
      - name: running
      - matchmode: contains
      - template: "Running Longterm Fetch and Place"
      - message: "Started scenario execution"
    - item:
      - name: done
      - matchmode: contains
      - template: "Done with LTFnP"
      - message: "Scenario completed"
  - quithooks:
    - item:
      - name: unhandled_condition
      - matchmode: contains
      - template: "unhandled condition in --disable-debugger mode, quitting"
      - message: "Unhandled condition"
  - timeout: 3600
- worker:
  - command: rosrun
  - parameters:
    - ltfnp_executive
    - package_log.sh
  - checklist:
    - item:
      - name: packaging_done
      - matchmode: contains
      - template: "Packaging complete"
      - message: "Packaging complete"
  - timeout: 1200
- cleaner:
  - command: rosrun
  - parameters:
    - ltfnp_executive
    - kill_all_relevant.sh
  - checklist:
    - item:
      - name: cleanup_done
      - matchmode: contains
      - template: "Cleanup done."
      - message: "Cleanup done."