- worker:
  - command: roslaunch
  - parameters:
    - ltfnp_executive
    - ltfnp_simulation.launch
  - checklist:
    - item:
      - name: moveit
      - matchmode: match
      - template: "All is well! Everyone is happy! You can start planning now!"
      - message: "MoveIt! launched successfully"
    - item:
      - name: attache
      - matchmode: contains
      - template: "Attache plugin loaded"
      - message: "Attache plugin present"
    - item:
      - name: spawn_model
      - matchmode: match
      - template: "spawn_model script started"
      - message: "Gazebo accepts spawn_model requests"
    - item:
      - name: reasoning
      - matchmode: contains
      - template: "ltfnp_reasoning/prolog/init.pl compiled"
      - message: "Reasoning started successfully"
    - item:
      - name: gzclient
      - matchmode: contains
      - template: "Connected to gazebo master"
      - message: "Gazebo Client successfully connected to gzserver"
  - timeout: 120
- worker:
  - command: rosrun
  - parameters:
    - semrec
    - semrec
  - checklist:
    - item:
      - name: initialize
      - matchmode: contains
      - template: "Initialization complete. You can start using the system now."
      - message: "Semrec Initialized"
  - timeout: 5
- worker:
  - command: rosrun
  - parameters:
    - ltfnp_executive
    - prep_mongodb.sh
  - checklist:
    - item:
      - name: prep_db
      - matchmode: contains
      - template: "MongoDB shell"
      - message: "MongoDB Logging started"
  - timeout: 10
- worker:
  - command: rosrun
  - parameters:
    - ltfnp_executive
    - start.sh
  - checklist:
    - item:
      - name: connect_ros
      - matchmode: contains
      - template: "Connecting to ROS"
      - message: "Connecting to ROS"
    - item:
      - name: running
      - matchmode: contains
      - template: "Running Longterm Fetch and Place"
      - message: "Started scenario execution"
    - item:
      - name: done
      - matchmode: contains
      - template: "Done with LTFnP"
      - message: "Scenario completed"
  - timeout: 1800
- worker:
  - command: rosrun
  - parameters:
    - ltfnp_executive
    - package_log.sh
  - timeout: 60
