meta-information:
  author: "Jan Winkler"
  email: winkler@cs.uni-bremen.de
  website:
  version: 0.2.0
changelog:
  - author: "Jan Winkler"
    email: winkler@cs.uni-bremen.de
    date: 2016-11-19
    changeset:
      - Moved to new YAML format for experiment description
      - Added meta information and task variances
task-variances:
  meal-seat-amount:
    label: "Amount of meal seats to set"
    value-type: [integer, range]
    value-range: [1, 2]
    default: [1, 2]
    distribution: normal
  object-availability-factor:
    label: "Percentage of objects spawned based on how many are required to solve the task"
    value-type: [percentage, range]
    value-range: [0, 3]
    default: [1, 1]
    distribution: normal
  allowed-arms:
    label: "Arms the PR2 is allowed to use"
    value-type: [multiple-choice]
    items: [["Left", left], ["Right", right]]
    allow-empty: false
    default: [left, right]
workers:
  - command: roslaunch
    parameters: [ltfnp_executive, ltfnp_simulation.launch]
    checklist:
    - name: moveit
      matchmode: match
      template: "All is well! Everyone is happy! You can start planning now!"
      message: "MoveIt! started successfully"
    - name: attache
      matchmode: contains
      template: "Attache plugin loaded"
      message: "Attache plugin present"
    - name: reasoning
      matchmode: contains
      template: "ltfnp_reasoning/prolog/init.pl compiled"
      message: "Reasoning started successfully"
    timeout: 360
  - command: rosrun
    parameters: [semrec, semrec, "-q", "-s"]
    checklist:
    - name: initialize
      matchmode: contains
      template: "Signify: semrec init complete"
      message: "Semrec Initialized"
    timeout: 15
  - command: rosrun
    parameters: [ltfnp_executive, prep_camera.sh, 1]
    checklist:
    - name: prep_cam
      matchmode: contains
      template: "Camera prepared"
      message: "Camera 1 prepared"
    timeout: 5
  - command: rosrun
    parameters: [ltfnp_executive, prep_camera.sh, 2]
    checklist:
    - name: prep_cam
      matchmode: contains
      template: "Camera prepared"
      message: "Camera 2 prepared"
    timeout: 5
  - command: rosrun
    parameters: [ltfnp_executive, prep_camera.sh, 3]
    checklist:
    - name: prep_cam
      matchmode: contains
      template: "Camera prepared"
      message: "Camera 3 prepared"
    timeout: 5
  - command: rosrun
    parameters: [ltfnp_executive, prep_camera.sh, 4]
    checklist:
    - name: prep_cam
      matchmode: contains
      template: "Camera prepared"
      message: "Camera 4 prepared"
    timeout: 5
  - command: rosrun
    parameters: [ltfnp_executive, prep_mongodb.sh]
    checklist:
    - name: prep_db
      matchmode: contains
      template: "MongoDB shell"
      message: "MongoDB Logging started"
    timeout: 10
  - command: rosrun
    parameters: [ltfnp_executive, start.sh, "((:headless t))"]
    append-variance: true
    checklist:
    - name: connect_ros
      matchmode: contains
      template: "Connecting to ROS"
      message: "Connecting to ROS"
    - name: running
      matchmode: contains
      template: "Running Longterm Fetch and Place"
      message: "Started scenario execution"
    - name: done
      matchmode: contains
      template: "Done with LTFnP"
      message: "Scenario completed"
    quithooks:
    - name: unhandled_condition
      matchmode: contains
      template: "unhandled condition in --disable-debugger mode, quitting"
      message: "Unhandled condition"
    timeout: 2700
  - command: rosrun
    parameters: [ltfnp_executive, package_log.sh]
    checklist:
    - name: packaging_done
      matchmode: contains
      template: "Packaging complete"
      message: "Packaging complete"
    timeout: 1200
cleaners:
  - command: rosrun
    parameters: [ltfnp_executive, kill_all_relevant.sh]
    checklist:
    - name: cleanup_done
      matchmode: contains
      template: "Cleanup done."
      message: "Cleanup done."
